<?xml version="1.0"?>
<package format="3">
  <name>handeye_calibration_ros</name>
  <version>0.1.0</version>
  <description>The handeye_calibration_ros package</description>

  <maintainer email="agilex@todo.com">Your Name</maintainer>
  <license>Apache-2.0</license>  

  <!-- Dependencies -->
  <!-- <exec_depend>urdf</exec_depend> -->
  <depend>rclpy</depend>
  <depend>ament_index_python</depend>
  <depend>cv_bridge</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <exec_depend>piper_description</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rqt_gui_py</exec_depend>
  <exec_depend>python3-pyqt5</exec_depend>
  <exec_depend>aruco_ros</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>orbbec_camera</exec_depend>
  <exec_depend>rqt_image_view</exec_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
</package>
